alter table public.profiles add column if not exists email text not null default '';
alter table public.profiles add column if not exists is_disabled boolean not null default false;

update public.profiles
set email = coalesce(auth_users.email, '')
from auth.users as auth_users
where public.profiles.id = auth_users.id
  and public.profiles.email = '';

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, phone, email, email_notifications, order_notifications)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', 'Пользователь'),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    coalesce(new.email, ''),
    coalesce((new.raw_user_meta_data ->> 'emailNotifications')::boolean, true),
    coalesce((new.raw_user_meta_data ->> 'orderNotifications')::boolean, true)
  )
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

create or replace function public.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and not is_disabled
  );
$$;

revoke all on function public.is_active_user() from public;
grant execute on function public.is_active_user() to authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'admin'
      and not is_disabled
  );
$$;

drop policy if exists "Users can read their own profile" on public.profiles;
drop policy if exists "Users can update their own profile data" on public.profiles;
drop policy if exists "Admins can manage profiles" on public.profiles;

create policy "Users can read their own active profile"
on public.profiles for select
to authenticated
using (
  (select auth.uid()) = id
  and not is_disabled
);

create policy "Admins can read profiles"
on public.profiles for select
to authenticated
using ((select public.is_admin()));

create policy "Users can update their own active profile"
on public.profiles for update
to authenticated
using (
  (select auth.uid()) = id
  and not is_disabled
)
with check (
  (select auth.uid()) = id
  and not is_disabled
);

create policy "Admins can manage profiles"
on public.profiles for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  logo text
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  image text,
  parent_id bigint references public.categories(id) on delete set null
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  article text not null unique,
  description text not null default '',
  price numeric not null,
  old_price numeric,
  discount numeric,
  category_slug text not null,
  brand_slug text,
  images jsonb not null default '[]'::jsonb,
  rating numeric not null default 0,
  reviews_count integer not null default 0,
  stock integer not null default 0,
  color text,
  compatibility jsonb not null default '[]'::jsonb,
  is_new boolean not null default false,
  is_popular boolean not null default false,
  is_sale boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  city text not null,
  street text not null,
  house text not null,
  apartment text,
  phone text not null,
  is_default boolean not null default false
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  unique (user_id, product_id)
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  unique (user_id, product_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  products jsonb not null default '[]'::jsonb,
  customer_name text not null,
  phone text not null,
  email text not null,
  delivery_method text not null,
  payment_method text not null,
  address jsonb,
  comment text,
  products_price numeric not null default 0,
  delivery_price numeric not null default 0,
  discount numeric not null default 0,
  total numeric not null default 0,
  status text not null default 'new',
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.brands enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.addresses enable row level security;
alter table public.cart_items enable row level security;
alter table public.favorites enable row level security;
alter table public.orders enable row level security;

drop policy if exists "Public can read catalog" on public.brands;
drop policy if exists "Public can read categories" on public.categories;
drop policy if exists "Public can read products" on public.products;
drop policy if exists "Admins can manage catalog" on public.brands;
drop policy if exists "Admins can manage categories" on public.categories;
drop policy if exists "Admins can manage products" on public.products;
drop policy if exists "Users manage own addresses" on public.addresses;
drop policy if exists "Users manage own cart" on public.cart_items;
drop policy if exists "Users manage own favorites" on public.favorites;
drop policy if exists "Users read own orders" on public.orders;
drop policy if exists "Users create own orders" on public.orders;
drop policy if exists "Admins read orders" on public.orders;
drop policy if exists "Admins manage orders" on public.orders;

create policy "Public can read catalog"
on public.brands for select to anon, authenticated using (true);

create policy "Public can read categories"
on public.categories for select to anon, authenticated using (true);

create policy "Public can read products"
on public.products for select to anon, authenticated using (true);

create policy "Admins can manage catalog"
on public.brands for all to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

create policy "Admins can manage categories"
on public.categories for all to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

create policy "Admins can manage products"
on public.products for all to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

create policy "Users manage own addresses"
on public.addresses for all to authenticated
using ((select auth.uid()) = user_id and (select public.is_active_user()))
with check ((select auth.uid()) = user_id and (select public.is_active_user()));

create policy "Users manage own cart"
on public.cart_items for all to authenticated
using ((select auth.uid()) = user_id and (select public.is_active_user()))
with check ((select auth.uid()) = user_id and (select public.is_active_user()));

create policy "Users manage own favorites"
on public.favorites for all to authenticated
using ((select auth.uid()) = user_id and (select public.is_active_user()))
with check ((select auth.uid()) = user_id and (select public.is_active_user()));

create policy "Users read own orders"
on public.orders for select to authenticated
using ((select auth.uid()) = user_id and (select public.is_active_user()));

create policy "Users create own orders"
on public.orders for insert to authenticated
with check ((select auth.uid()) = user_id and (select public.is_active_user()));

create policy "Admins manage orders"
on public.orders for update to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

grant select on public.brands, public.categories, public.products to anon, authenticated;
grant all on public.brands, public.categories, public.products to authenticated;
grant all on public.addresses, public.cart_items, public.favorites, public.orders to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.disable_user(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only an administrator can disable users';
  end if;

  if target_user_id = (select auth.uid()) then
    raise exception 'An administrator cannot disable their own account';
  end if;

  update public.profiles
  set is_disabled = true
  where id = target_user_id;
end;
$$;

revoke all on function public.disable_user(uuid) from public;
grant execute on function public.disable_user(uuid) to authenticated;

drop policy if exists "Users read own orders" on public.orders;
drop policy if exists "Users create own orders" on public.orders;
drop policy if exists "Admins manage orders" on public.orders;

create policy "Users read own orders"
on public.orders for select to authenticated
using (
  (select auth.uid()) = user_id
  and (select public.is_active_user())
);

create policy "Admins read orders"
on public.orders for select to authenticated
using ((select public.is_admin()));

create policy "Admins manage orders"
on public.orders for update to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

revoke insert, delete on public.orders from authenticated;
grant select, update on public.orders to authenticated;

create or replace function public.create_order(
  p_products jsonb,
  p_customer_name text,
  p_phone text,
  p_email text,
  p_delivery_method text,
  p_payment_method text,
  p_address jsonb default null,
  p_comment text default null
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := (select auth.uid());
  product_count integer;
  requested_lines integer;
  distinct_requested_lines integer;
  requested_count integer;
  calculated_products jsonb;
  calculated_products_price numeric;
  calculated_delivery_price numeric := case
    when p_delivery_method = 'courier' then 500
    else 0
  end;
  created_order public.orders;
begin
  if current_user_id is null or not public.is_active_user() then
    raise exception 'User is not authorized';
  end if;

  if p_delivery_method not in ('courier', 'pickup')
    or p_payment_method not in ('cash', 'card') then
    raise exception 'Invalid order method';
  end if;

  select count(*)
  into requested_lines
  from jsonb_to_recordset(coalesce(p_products, '[]'::jsonb))
    as item(product_id bigint, quantity integer);

  select count(distinct item.product_id)
  into distinct_requested_lines
  from jsonb_to_recordset(coalesce(p_products, '[]'::jsonb))
    as item(product_id bigint, quantity integer);

  select
    count(*),
    coalesce(sum(item.quantity), 0)
  into product_count, requested_count
  from jsonb_to_recordset(coalesce(p_products, '[]'::jsonb))
    as item(product_id bigint, quantity integer)
  join public.products product on product.id = item.product_id
  where item.quantity > 0
    and product.stock >= item.quantity;

  if requested_lines = 0
    or requested_lines <> distinct_requested_lines
    or product_count <> requested_lines
    or requested_count = 0 then
    raise exception 'Order must contain available products';
  end if;

  select
    jsonb_agg(jsonb_build_object(
      'productId', product.id,
      'name', product.name,
      'price', product.price,
      'quantity', item.quantity,
      'image', product.images ->> 0
    )),
    sum(product.price * item.quantity)
  into calculated_products, calculated_products_price
  from jsonb_to_recordset(coalesce(p_products, '[]'::jsonb))
    as item(product_id bigint, quantity integer)
  join public.products product on product.id = item.product_id
  where item.quantity > 0
    and product.stock >= item.quantity;

  insert into public.orders (
    user_id,
    products,
    customer_name,
    phone,
    email,
    delivery_method,
    payment_method,
    address,
    comment,
    products_price,
    delivery_price,
    discount,
    total,
    status
  )
  values (
    current_user_id,
    calculated_products,
    left(trim(p_customer_name), 200),
    left(trim(p_phone), 50),
    left(lower(trim(p_email)), 320),
    p_delivery_method,
    p_payment_method,
    p_address,
    left(trim(coalesce(p_comment, '')), 1000),
    calculated_products_price,
    calculated_delivery_price,
    0,
    calculated_products_price + calculated_delivery_price,
    'new'
  )
  returning * into created_order;

  return created_order;
end;
$$;

revoke all on function public.create_order(jsonb, text, text, text, text, text, jsonb, text)
from public;
grant execute on function public.create_order(jsonb, text, text, text, text, text, jsonb, text)
to authenticated;
